/*
inventory Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v1
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
	"time"
)

// checks if the InventoryStockItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InventoryStockItem{}

// InventoryStockItem struct for InventoryStockItem
type InventoryStockItem struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
	Sku *string `json:"sku,omitempty"`
	OutOfStockThreshold *int32 `json:"outOfStockThreshold,omitempty"`
	Qty *int32 `json:"qty,omitempty"`
	QtyCommitted *int32 `json:"qtyCommitted,omitempty"`
	QtySalable *int32 `json:"qtySalable,omitempty"`
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// NewInventoryStockItem instantiates a new InventoryStockItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryStockItem() *InventoryStockItem {
	this := InventoryStockItem{}
	return &this
}

// NewInventoryStockItemWithDefaults instantiates a new InventoryStockItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryStockItemWithDefaults() *InventoryStockItem {
	this := InventoryStockItem{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *InventoryStockItem) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *InventoryStockItem) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *InventoryStockItem) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InventoryStockItem) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InventoryStockItem) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InventoryStockItem) SetId(v string) {
	o.Id = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *InventoryStockItem) GetSku() string {
	if o == nil || IsNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetSkuOk() (*string, bool) {
	if o == nil || IsNil(o.Sku) {
		return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *InventoryStockItem) HasSku() bool {
	if o != nil && !IsNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *InventoryStockItem) SetSku(v string) {
	o.Sku = &v
}

// GetOutOfStockThreshold returns the OutOfStockThreshold field value if set, zero value otherwise.
func (o *InventoryStockItem) GetOutOfStockThreshold() int32 {
	if o == nil || IsNil(o.OutOfStockThreshold) {
		var ret int32
		return ret
	}
	return *o.OutOfStockThreshold
}

// GetOutOfStockThresholdOk returns a tuple with the OutOfStockThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetOutOfStockThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.OutOfStockThreshold) {
		return nil, false
	}
	return o.OutOfStockThreshold, true
}

// HasOutOfStockThreshold returns a boolean if a field has been set.
func (o *InventoryStockItem) HasOutOfStockThreshold() bool {
	if o != nil && !IsNil(o.OutOfStockThreshold) {
		return true
	}

	return false
}

// SetOutOfStockThreshold gets a reference to the given int32 and assigns it to the OutOfStockThreshold field.
func (o *InventoryStockItem) SetOutOfStockThreshold(v int32) {
	o.OutOfStockThreshold = &v
}

// GetQty returns the Qty field value if set, zero value otherwise.
func (o *InventoryStockItem) GetQty() int32 {
	if o == nil || IsNil(o.Qty) {
		var ret int32
		return ret
	}
	return *o.Qty
}

// GetQtyOk returns a tuple with the Qty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetQtyOk() (*int32, bool) {
	if o == nil || IsNil(o.Qty) {
		return nil, false
	}
	return o.Qty, true
}

// HasQty returns a boolean if a field has been set.
func (o *InventoryStockItem) HasQty() bool {
	if o != nil && !IsNil(o.Qty) {
		return true
	}

	return false
}

// SetQty gets a reference to the given int32 and assigns it to the Qty field.
func (o *InventoryStockItem) SetQty(v int32) {
	o.Qty = &v
}

// GetQtyCommitted returns the QtyCommitted field value if set, zero value otherwise.
func (o *InventoryStockItem) GetQtyCommitted() int32 {
	if o == nil || IsNil(o.QtyCommitted) {
		var ret int32
		return ret
	}
	return *o.QtyCommitted
}

// GetQtyCommittedOk returns a tuple with the QtyCommitted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetQtyCommittedOk() (*int32, bool) {
	if o == nil || IsNil(o.QtyCommitted) {
		return nil, false
	}
	return o.QtyCommitted, true
}

// HasQtyCommitted returns a boolean if a field has been set.
func (o *InventoryStockItem) HasQtyCommitted() bool {
	if o != nil && !IsNil(o.QtyCommitted) {
		return true
	}

	return false
}

// SetQtyCommitted gets a reference to the given int32 and assigns it to the QtyCommitted field.
func (o *InventoryStockItem) SetQtyCommitted(v int32) {
	o.QtyCommitted = &v
}

// GetQtySalable returns the QtySalable field value if set, zero value otherwise.
func (o *InventoryStockItem) GetQtySalable() int32 {
	if o == nil || IsNil(o.QtySalable) {
		var ret int32
		return ret
	}
	return *o.QtySalable
}

// GetQtySalableOk returns a tuple with the QtySalable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetQtySalableOk() (*int32, bool) {
	if o == nil || IsNil(o.QtySalable) {
		return nil, false
	}
	return o.QtySalable, true
}

// HasQtySalable returns a boolean if a field has been set.
func (o *InventoryStockItem) HasQtySalable() bool {
	if o != nil && !IsNil(o.QtySalable) {
		return true
	}

	return false
}

// SetQtySalable gets a reference to the given int32 and assigns it to the QtySalable field.
func (o *InventoryStockItem) SetQtySalable(v int32) {
	o.QtySalable = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *InventoryStockItem) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *InventoryStockItem) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *InventoryStockItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *InventoryStockItem) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryStockItem) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *InventoryStockItem) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *InventoryStockItem) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

func (o InventoryStockItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InventoryStockItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !IsNil(o.OutOfStockThreshold) {
		toSerialize["outOfStockThreshold"] = o.OutOfStockThreshold
	}
	if !IsNil(o.Qty) {
		toSerialize["qty"] = o.Qty
	}
	if !IsNil(o.QtyCommitted) {
		toSerialize["qtyCommitted"] = o.QtyCommitted
	}
	if !IsNil(o.QtySalable) {
		toSerialize["qtySalable"] = o.QtySalable
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableInventoryStockItem struct {
	value *InventoryStockItem
	isSet bool
}

func (v NullableInventoryStockItem) Get() *InventoryStockItem {
	return v.value
}

func (v *NullableInventoryStockItem) Set(val *InventoryStockItem) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryStockItem) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryStockItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryStockItem(val *InventoryStockItem) *NullableInventoryStockItem {
	return &NullableInventoryStockItem{value: val, isSet: true}
}

func (v NullableInventoryStockItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryStockItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


