/*
inventory.proto

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: version not set
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package inventory

import (
	"encoding/json"
)

// InventoryGetQtySalableResponse struct for InventoryGetQtySalableResponse
type InventoryGetQtySalableResponse struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
	Sku *string `json:"sku,omitempty"`
	QtySalable *int32 `json:"qtySalable,omitempty"`
}

// NewInventoryGetQtySalableResponse instantiates a new InventoryGetQtySalableResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInventoryGetQtySalableResponse() *InventoryGetQtySalableResponse {
	this := InventoryGetQtySalableResponse{}
	return &this
}

// NewInventoryGetQtySalableResponseWithDefaults instantiates a new InventoryGetQtySalableResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInventoryGetQtySalableResponseWithDefaults() *InventoryGetQtySalableResponse {
	this := InventoryGetQtySalableResponse{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *InventoryGetQtySalableResponse) GetTenantId() string {
	if o == nil || isNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryGetQtySalableResponse) GetTenantIdOk() (*string, bool) {
	if o == nil || isNil(o.TenantId) {
    return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *InventoryGetQtySalableResponse) HasTenantId() bool {
	if o != nil && !isNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *InventoryGetQtySalableResponse) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InventoryGetQtySalableResponse) GetId() string {
	if o == nil || isNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryGetQtySalableResponse) GetIdOk() (*string, bool) {
	if o == nil || isNil(o.Id) {
    return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InventoryGetQtySalableResponse) HasId() bool {
	if o != nil && !isNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InventoryGetQtySalableResponse) SetId(v string) {
	o.Id = &v
}

// GetSku returns the Sku field value if set, zero value otherwise.
func (o *InventoryGetQtySalableResponse) GetSku() string {
	if o == nil || isNil(o.Sku) {
		var ret string
		return ret
	}
	return *o.Sku
}

// GetSkuOk returns a tuple with the Sku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryGetQtySalableResponse) GetSkuOk() (*string, bool) {
	if o == nil || isNil(o.Sku) {
    return nil, false
	}
	return o.Sku, true
}

// HasSku returns a boolean if a field has been set.
func (o *InventoryGetQtySalableResponse) HasSku() bool {
	if o != nil && !isNil(o.Sku) {
		return true
	}

	return false
}

// SetSku gets a reference to the given string and assigns it to the Sku field.
func (o *InventoryGetQtySalableResponse) SetSku(v string) {
	o.Sku = &v
}

// GetQtySalable returns the QtySalable field value if set, zero value otherwise.
func (o *InventoryGetQtySalableResponse) GetQtySalable() int32 {
	if o == nil || isNil(o.QtySalable) {
		var ret int32
		return ret
	}
	return *o.QtySalable
}

// GetQtySalableOk returns a tuple with the QtySalable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InventoryGetQtySalableResponse) GetQtySalableOk() (*int32, bool) {
	if o == nil || isNil(o.QtySalable) {
    return nil, false
	}
	return o.QtySalable, true
}

// HasQtySalable returns a boolean if a field has been set.
func (o *InventoryGetQtySalableResponse) HasQtySalable() bool {
	if o != nil && !isNil(o.QtySalable) {
		return true
	}

	return false
}

// SetQtySalable gets a reference to the given int32 and assigns it to the QtySalable field.
func (o *InventoryGetQtySalableResponse) SetQtySalable(v int32) {
	o.QtySalable = &v
}

func (o InventoryGetQtySalableResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !isNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !isNil(o.Sku) {
		toSerialize["sku"] = o.Sku
	}
	if !isNil(o.QtySalable) {
		toSerialize["qtySalable"] = o.QtySalable
	}
	return json.Marshal(toSerialize)
}

type NullableInventoryGetQtySalableResponse struct {
	value *InventoryGetQtySalableResponse
	isSet bool
}

func (v NullableInventoryGetQtySalableResponse) Get() *InventoryGetQtySalableResponse {
	return v.value
}

func (v *NullableInventoryGetQtySalableResponse) Set(val *InventoryGetQtySalableResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableInventoryGetQtySalableResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableInventoryGetQtySalableResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInventoryGetQtySalableResponse(val *InventoryGetQtySalableResponse) *NullableInventoryGetQtySalableResponse {
	return &NullableInventoryGetQtySalableResponse{value: val, isSet: true}
}

func (v NullableInventoryGetQtySalableResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInventoryGetQtySalableResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


